apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentloader-deployment
  labels:
    app: StudentLoader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: StudentLoader
  template:
    metadata:
      labels:
        app: StudentLoader
    spec:
      containers:
      - name: studentloader
        image: gcr.io/jasondel-test-project/studentloader:v1.2
        volumeMounts:
        - name: smb-volume
          mountPath: /data
        - name: connection-strings
          mountPath: "/Cymbal/secret"
          readOnly: true  
      volumes:
      - name: smb-volume
        flexVolume:
          driver: "microsoft.com/smb.cmd"
          secretRef:
            name: "smb-secret"
          options:
            source: "\\\\10.96.16.2\\smbshare"
      - name: connection-strings
        secret:
          secretName: connection-strings            
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: windows
        cloud.google.com/gke-os-distribution: windows_ltsc    