apiVersion: apps/v1
kind: Deployment
metadata:
  name: cymbalfile-deployment
  labels:
    app: CymbalFileProcessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CymbalFileProcessor
  template:
    metadata:
      labels:
        app: CymbalFileProcessor
    spec:
      containers:
      - name: cymbalfile
        image: gcr.io/jasondel-test-project/cymbalfileservice:v2
        volumeMounts:
        - name: smb-volume
          mountPath: /data
      volumes:
      - name: smb-volume
        flexVolume:
          driver: "microsoft.com/smb.cmd"
          secretRef:
            name: "smb-secret"
          options:
            source: "\\\\10.96.16.2\\smbshare"
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: windows
        cloud.google.com/gke-os-distribution: windows_ltsc    